# Puppeteer için gerekli sistem paketleri
[phases.setup]
nixPkgs = ["nodejs_20"]

# Chromium ve kütüphaneler apt ile kurulsun
aptPkgs = [
  "chromium",
  "chromium-driver",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libasound2t64",
  "libpangocairo-1.0-0",
  "libxss1",
  "libgtk-3-0",
  "libxshmfence1",
  "libglu1",
  "libdrm2",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "fonts-liberation",
  "libappindicator3-1",
  "xdg-utils"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[start]
cmd = "node server.js"